# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-29 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentid', models.AutoField(db_column='appointmentID', primary_key=True, serialize=False)),
                ('astarttime', models.DateTimeField(blank=True, db_column='aStartTime', null=True)),
                ('aendtime', models.DateTimeField(blank=True, db_column='aEndTime', null=True)),
                ('requestcomment', models.CharField(blank=True, db_column='requestComment', max_length=255, null=True)),
                ('requesttype', models.CharField(blank=True, db_column='requestType', max_length=10, null=True)),
                ('timeofsubmittingrequest', models.DateTimeField(blank=True, db_column='timeOfSubmittingRequest', null=True)),
                ('requeststarttime', models.DateTimeField(blank=True, db_column='requestStartTime', null=True)),
                ('requestendtime', models.DateTimeField(blank=True, db_column='requestEndTime', null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('counselorid', models.CharField(db_column='counselorID', max_length=10, primary_key=True, serialize=False)),
                ('counselorlname', models.CharField(blank=True, db_column='counselorLName', max_length=50, null=True)),
                ('counselorfname', models.CharField(blank=True, db_column='counselorFName', max_length=50, null=True)),
                ('counselorpassword', models.CharField(blank=True, db_column='counselorPassword', max_length=50, null=True)),
            ],
            options={
                'db_table': 'counselor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('educatorid', models.CharField(db_column='educatorID', max_length=10, primary_key=True, serialize=False)),
                ('educatorlname', models.CharField(blank=True, db_column='educatorLName', max_length=50, null=True)),
                ('educatorfname', models.CharField(blank=True, db_column='educatorFName', max_length=50, null=True)),
                ('educatortype', models.CharField(blank=True, db_column='educatorType', max_length=20, null=True)),
                ('educatoremailaddress', models.CharField(blank=True, db_column='educatorEmailAddress', max_length=50, null=True)),
                ('educatorpassword', models.CharField(blank=True, db_column='educatorPassword', max_length=50, null=True)),
            ],
            options={
                'db_table': 'educator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incidentid', models.AutoField(db_column='incidentID', primary_key=True, serialize=False)),
                ('incidenttype', models.CharField(blank=True, db_column='incidentType', max_length=45, null=True)),
                ('location', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'incident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(db_column='studentID', max_length=10, primary_key=True, serialize=False)),
                ('studentlname', models.CharField(blank=True, db_column='studentLName', max_length=50, null=True)),
                ('studentfname', models.CharField(blank=True, db_column='studentFName', max_length=50, null=True)),
                ('studentemailaddress', models.CharField(blank=True, db_column='studentEmailAddress', max_length=50, null=True)),
                ('studentage', models.IntegerField(blank=True, db_column='studentAge', null=True)),
                ('studentdob', models.DateField(blank=True, db_column='studentDOB', null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('program', models.CharField(blank=True, max_length=30, null=True)),
                ('studentpassword', models.CharField(blank=True, db_column='studentPassword', max_length=50, null=True)),
                ('studenttype', models.CharField(blank=True, db_column='studentType', max_length=15, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentprofile',
            fields=[
                ('profileid', models.CharField(db_column='profileID', max_length=10, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('seq', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('studentprofilecol', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'studentprofile',
                'managed': False,
            },
        ),
    ]
