# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed4all', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='counselor',
            table='Counselor',
        ),
        migrations.AlterModelTable(
            name='educator',
            table='Educator',
        ),
        migrations.AlterModelTable(
            name='incident',
            table='Incident',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
        migrations.AlterModelTable(
            name='studentprofile',
            table='StudentProfile',
        ),
    ]
