# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-01 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed4all', '0002_auto_20170429_1811'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='Appointment',
        ),
    ]
